// console.dir(document)
// console.log(document.doctype)
// console.log(document.URL)
// console.log(document.lastModified)
// console.log(document.head)
// console.log(document.body)
// console.log(document.forms)
console.log(document.all)
